---
title: Bugo
baseURL: "/"
languageCode: en
summaryLength: 25
googleAnalytics: ''
paginate: 10
enableEmoji: false
outputs:
  home:
  - html
  - rss
  - json
  page:
  - html
  - rss
  - json
  section:
  - html
  - rss
  - json
  term:
  - html
  - rss
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: false
  tdewolff:
    css:
      decimals: -1
      keepCSS2: true
    html:
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepWhitespace: false
    js: {}
    json: {}
    svg:
      decimals: -1
    xml:
      keepWhitespace: false
metaDataFormat: yaml
terms:
  time_period: time_period
  quadrant: quadrants
  universe: universes
  affiliation: affiliations
  type: types
  franchise: franchise
  designer: designer
  designers: designers
related:
  threshold: 80
  includeNewer: true
  toLower: false
  indices:
  - name: time_period
    weight: 100
  - name: affiliation
    weight: 60
  - name: quadrant
    weight: 50
  - name: universe
    weight: 30
  - name: types
    weight: 20
  - name: franchise
    weight: 10
theme:
# Image Handling
- sb-cloudinary
# - sb-netlify-large-media
# Layouts
- sb-search
- sb-blocks
- sb-landing-page
- sb-section
# - sb-sidebar
- sb-utilities
- custom
# Base Theme and API
- sb
- sb-api
