---
baseURL:
canonifyURLs: true
enableGitInfo: true
enableInlineShortcodes: true
showSearchInMain: false
enableOffCanvasSearch: true
showWCAG: true
relatedPostsTitle: Related
latestPostsTitle: Recent
seoLogo: /uploads/rldqp4lna4rbp12ivn7o.png
blogSlug: blog