---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Posts
  create: documents
  match: "**/*"
  templates:
  - post
  - blog-list
- type: directory
  path: content/getting-started
  label: Getting Started
  create: all
  match: "**/*"
  templates:
  - page
  - section-list
  - list-page
- type: directory
  path: content/docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - page
  - list-page
  - section-list
- type: directory
  path: content
  label: Pages
  create: all
  match: "**/*"
  exclude: "{blog,getting-started,docs}/**/*"
  templates:
  - page
  - page-contact
  - page-legal
  - list-page
  - landing-page
  - section-list
- type: document
  path: data/testimonials.yaml
  label: Testimonials
- type: heading
  label: Options
- type: document
  path: data/organization.yaml
  label: Site
- type: document
  path: data/locations.yaml
  label: Locations
- type: document
  path: data/categories.yaml
  label: Categories
upload_dir: ''
public_path: https://res.cloudinary.com/startrekdesignproject-com/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=development
  - HUGO_VERSION=0.74.3
  - GOOGLE_KEY=false
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --renderToDisk -d public
version: 0.71.1
